library(dplyr)
library(lubridate)
data <- read.table("~/Desktop/coursera/household_power_consumption.txt", sep=";", quote="\"",skip=1,stringsAsFactors=FALSE,col.names=c("Date","Time","Global Active Power","Global Reactive Power","Voltage","Global intensity","Submetering 1","Submetering 2", "Submetering 3"))
all_data<-mutate(data,Date=as.Date(data$Date, format = "%d/%m/%Y"))
all_data<-filter(all_data,Date=="2007-02-02"|Date=="2007-02-01")
all_data<-mutate(all_data,Weekday=as.character(wday(all_data$Date,label=TRUE)))
all_data<-mutate(all_data,New_date=paste(all_data$Date,all_data$Time,sep=" "))
x<-strptime(all_data$New_date,"%Y-%m-%d %H:%M:%S")
y<-as.numeric(all_data$Global.Active.Power)
plot(x,y,type="o",pch=".",ylab="Global Active Power (kilowatts)",xlab="")
