library(dplyr)
library(lubridate)
data <- read.table("~/Desktop/coursera/household_power_consumption.txt", sep=";", quote="\"",skip=1,stringsAsFactors=FALSE,col.names=c("Date","Time","Global Active Power","Global Reactive Power","Voltage","Global intensity","Submetering 1","Submetering 2", "Submetering 3"))
all_data<-mutate(data,Date=as.Date(data$Date, format = "%d/%m/%Y"))
all_data<-filter(all_data,Date=="2007-02-02"|Date=="2007-02-01")
all_data<-mutate(all_data,Weekday=as.character(wday(all_data$Date,label=TRUE)))
all_data<-mutate(all_data,New_date=paste(all_data$Date,all_data$Time,sep=" "))
x<-strptime(all_data$New_date,"%Y-%m-%d %H:%M:%S")
y<-as.numeric(all_data$Submetering.1)
w<-as.numeric(all_data$Submetering.2)
z<-as.numeric(all_data$Submetering.3)
g_range<-range(0,y,z,w)
plot(x,z,type="o",ylim=g_range,pch=".",col="blue",ylab="energy sub metering")
par(new=TRUE)
plot(x,y,type="o",ylim=g_range,pch=".",ylab=" ",xlab=" ")
par(new=TRUE)
plot(x,w,type="o",ylim=g_range,pch=".",col="red",,ylab=" ",xlab=" ")
legend("topright",legend=c('Sub_metering_1',"Sub_metering_2","Sub_metering_3"),pch=c("-","-","-"),col=c("black","red","blue"))
